# .github/workflows/deploy.yml
name: Deploy frontend to S3

on:
  push:
    branches:
      - main  # 好きなブランチに変更してOK

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.6'   # プロジェクトの Node に合わせる

      - name: Install dependencies
        run: npm ci

      - name: Debug Variable
        run: echo "変数の値は [ ${{ vars.VITE_API_URL }} ] です"

      - name: Build
        run: npm run build
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Sync S3
        run: aws s3 sync dist/ s3://task-app-s3-ryuuiti/ --delete
